apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    type: webapp
    environment: dev
spec:
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          hostPort: 8090
          protocol: TCP
        volumeMounts:
          - name: nginx-data
            mountPath: "/usr/share/nginx/html" #mount this location inside container to PV
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-pvc