apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-hostpath
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/var/tmp"